apiVersion: v1
kind: Pod
metadata:
  name: debian
spec:
  containers:
    - name: debian
      image: artifacts.microchip.com:7999/microchip/citd/debian:1.0.0-stable
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 4Gi
        limits:
          cpu: 2
          memory: 8Gi
